### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by FiReTiTi** [facebookresearch/detectron2#956]
When installing `detectron2` on a cluster, I get multiple errors, mainly PyTorch related, like:

    site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:211:80: error: redeclaration of 'const at::Tensor& args#0'
    site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:211:80: error: redeclaration of 'bool& args#3'
    site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:208:38: error: member 'c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = void; Args = {const at::Tensor&, const at::Tensor&, bool, bool}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>::<args#1 capture>' is uninitialized reference

I don't copy the full trace because it's huge.

How can I fix it?

## Instructions To Reproduce the Issue:

1. None
2. `pip install 'git+https://github.com/facebookresearch/detectron2.git'`
3. See following post

## Environment:

Cluster on Centos 7.7
gcc 9.2.0_1
cuda 10 (nvcc 10.0.130)

sys.platform            linux
Python                  3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
numpy                   1.18.1
detectron2._C           failed to import
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.4.0 @/home/users/titi/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0                   Tesla K40m
CUDA_HOME               /usr/local/cuda-10.0
NVCC                    Cuda compilation tools, release 10.0, V10.0.130
Pillow                  7.0.0
torchvision             0.5.0 @/home/users/titi/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
----------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by FiReTiTi** [comment]
Done

**Comment by FiReTiTi** [comment]
The log is to big (~10Mo) to be copy/paste in this thread.

**Comment by ppwwyyxx** [comment]
You can at least provide other sections. Logs maybe could be uploaded as files

**Comment by FiReTiTi** [comment]
Here is the full error file.
[errors.txt](https://github.com/facebookresearch/detectron2/files/4258920/errors.txt)

**Comment by ppwwyyxx** [comment]
The "Environment" section of the issue template is still missing.

**Comment by FiReTiTi** [comment]
Detectron failed at installation, none of the commands succeeded.

**Comment by ppwwyyxx** [comment]
```
wget https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py
python collect_env.py
```
it does not require installation.

**Comment by ppwwyyxx** [comment]
Thanks for the updated information.
Pytorch 1.4.0 does not compile with gcc 9. See https://github.com/pytorch/pytorch/issues/32277.

**Comment by FiReTiTi** [comment]
I had to go down GCC7.
